FROM apache/airflow:2.10.3

USER root

# Install Java 17 (required for Spark and Kafka)
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    openjdk-17-jre-headless \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

USER airflow

# Install Python packages for streaming processing
RUN pip install --no-cache-dir \
    "apache-airflow==2.10.3" \
    apache-airflow-providers-apache-spark==2.1.3 \
    pyspark==3.5.0 \
    confluent-kafka==2.3.0 \
    kafka-python==2.0.2 \
    colorama==0.4.6 \
    python-dotenv==1.0.0 \
    requests